### PR TITLE
Fix double-free issue in `into_owner` method

### LINKED ISSUE #24: Double-free with `into_owner`
```rs
use std::cell::Cell;

use self_cell::self_cell;

type O = Cell<Option<Box<u8>>>;

self_cell! {
    struct S {
        owner: O,
        #[covariant]
        dependent: D,
    }
}

struct D<'a>(&'a O);

impl Drop for D<'_> {
    fn drop(&mut self) {
        self.0.take();
    }
}

fn main() {
    let s = S::new(Cell::new(Some(Box::new(42))), |o| D(o));
    s.into_owner();
}
```
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/small_pg`
thread 'main' panicked at 'explicit panic', src/main.rs:20:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
free(): double free detected in tcache 2
[1]    394203 IOT instruction (core dumped)  cargo r
```

The underlying problem is

https://github.com/Voultapher/self_cell/blob/ae22d0f26d4a63be3fa9bbfe4c98b7b0246630ea/src/unsafe_self_cell.rs#L90-L96

where the owner is read **before** dependent is dropped, so dropping dependent can access the original owner, but `into_owner` returns the copy created *beforehand*.

<hr>

I have a branch that fixes this as well as some memory leaks: https://github.com/steffahn/self_cell/compare/fix_drop_order...fix_double_free_and_leaks

The branch is based on #21 (one of the memory leaks is in `drop_joined`), so I’ll only open a PR after #21 is merged. So consider not to release a new version yet after merging #21 😉

### PR DESCRIPTION
**Pull request by steffahn**
Closes #24

### CODE REVIEW

**Comment by steffahn** [comment]
FFS, a merge conflict. Ah, probably on the import? …

**Comment by steffahn** [comment]
Rebased.

**Comment by Voultapher** [comment]
Looks good, going to push minor style changes.

**Comment by steffahn** [comment]
FYI, the way the `into_owner_without_panic` _name_ is to differentiate from a `into_owner_with_panic` that I’d like to add later for testing the leak-prevention in a later PR.

**Pull request merged**
