### PR TITLE
Restore compatibility with Rust 1.42 via Polyfill

### PR DESCRIPTION
**Pull request by mitsuhiko**
This is an alternative implementation of https://github.com/Voultapher/self_cell/pull/31 which is based on polyfilling the function for older rust versions.  It's implemented by shelling out to rustc and checking the version.

This is fine because old rust versions did not perform optimizations by this incorrect cast and this is known to work on affected compilers.

### CODE REVIEW

**Comment by steffahn** [comment]
Pros and cons of doing this manually vs using [rustversion](https://docs.rs/rustversion/) crate?

**Comment by mitsuhiko** [comment]
The main reason I opted against rustversion is that it's quite a heavy crate. That said, it's not unlikely that crate is showing up somewhere in the dependency chain already. However it turns out that rustversion is not in use on our of our largest crates we have at sentry (the relay project with 500+ dependencies) so I figured it's not completely unreasonable to assume people might not be using it yet.

**Comment by mitsuhiko** [comment]
Actually I might be wrong on it being heavy. I thought it was using `proc_macro` but it might not?

**Comment by mitsuhiko** [comment]
Nevermind I was wrong. Might be worth using rustversion then. It's a single crate dependency. I can change the PR if that's preferred.

**Comment by mitsuhiko** [comment]
I changed it. Turns out rustversion hasn't been using syn and proc-macro2 for more than a year now. That makes it a relatively lightweight dependency and it's also saving one extra shelling out to rustc if the crate is already used elsewhere.

**Comment by steffahn** [comment]
If an additional dependency for `self_cell` is a concern, the conditional compilation and it's `rustversion` dependency could also be placed behind a feature gate. This would mean that users without need for low MSRV support could potentially spare the shelling out entirely.

**Comment by Voultapher** [comment]
Requiring build.rs and shelling out is not great. And if possible I'd like to keep the 0 Dependency promise. I have an idea, let me try that.

**Comment by steffahn** [comment]
We could consider generally switching to a layout more like `ouroboros`, where the owner is stored behind [`AliasableBox`](https://docs.rs/aliasable/0.1.3/aliasable/boxed/struct.AliasableBox.html) (which can be re-implementeed without any dependency), and the dependent is stored inline as a struct field. This would also save the indirection when accessing the dependent.

**Comment by mitsuhiko** [comment]
I toyed around a bit more but I can't think of a way to avoid the `rustversion` or `build.rs` dependency for the approach of this PR.

**Comment by Voultapher** [comment]
> We could consider generally switching to a layout more like `ouroboros`, where the owner is stored behind [`AliasableBox`](https://docs.rs/aliasable/0.1.3/aliasable/boxed/struct.AliasableBox.html) (which can be re-implementeed without any dependency), and the dependent is stored inline as a struct field. This would also save the indirection when accessing the dependent.

I've thought about this a couple times. The main perf difference comes from using https://crates.io/crates/stable_deref_trait and there a couple of reasons why I don't think that's a good fit for self_cell.

- It breaks the promise of being fully safe-to-use. That layout only works thanks to the unsafe marker traits of StableDeref. Which creates a rift for user types vs. built-in types, of course user types could be boxed but then we are back at the beginning.
- The error messages get worse if the type does not implement StableDeref, I've stumbled across a couple times myself when playing around with ouroboros, I want a library that's as easy as possible to use.
- It breaks the 0 dependencies appeal
- The perf difference as seen in the benchmarks and real world projects (fluent, wikijump) is negligible for real world stuff where you likely do more than just de-referencing self_cell.

We can't really store the dependent inline with the current interface. Vec turns into Slice, but self_cell allows borrowing the entire owner, which wouldn't be move safe. Also another potential source of user confusion that goes against my goal of easy-to-use.

**Comment by Voultapher** [comment]
FYI, I have a rough sketch of a detailed break-down of the differences between ouroboros and self_cell and when which ones is more appropriate in my head. I plan to write that down at some point.

**Comment by steffahn** [comment]
@Voultapher note that ouroboros currently does not use `StableDeref` anymore, instead it just boxes every borrowed field in an `AliasableBox`. The difference, AFAIK, is that `ouroboros` would handle a self-cell-style struct (single owner, single shared borrow of the owner) by boxing only the owner, while `self_cell` boxes both the owner and the dependent (but it’s putting them together into the same box).

What I’m proposing is basically just to move the dependent out of the indirection. I.e. put the dependent directly as a field (of type `DependentStatic`) into `UnsafeSelfCell` and remove the need for `JoinedCell`. The side-effect of this change is that the use-case of `addr_of_mut` also disappears.

**Comment by Voultapher** [comment]
@steffahn interesting didn't know that, thanks for clarifying. Currently self_cell type erases the lifetime and never stores `Dependent<'a>` as `Dependent<'static>`, which I consider being prudent, who knows what future compilers think of such 'lie'. I don't see how that guarantee could be maintained while storing the dependent inline.

**Comment by Voultapher** [comment]
Resolved in #33

**Pull request closed without merging**
